### ISSUE TITLE
Converting a SEXP matrix to big.matrix in C++

### ISSUE THREAD

**Issue by cdeterman** [kaneplusplus/bigalgebra#2]
I am currently toying with some `RcppArmadillo` functionality to improve bigalgebra and have reached a problem that I hope you have some ideas.  Generically speaking, I can creating a new arma matrix in the C++ world from two R matrices.  It is quite simple to convert back to a SEXP matrix with Rcpp's `wrap` function.  I thought, after looking at the other functions like `dgemm` I could do something like following at the end of a function where `pC` is a double pointer, my new SEXP matrix is `C` and `C_isBM` is TRUE.

```
pC = make_double_ptr (C, C_isBM);
PROTECT(ans = C);
Rf_unprotect(1);
return ans;
```

Unforunately this results in an error:

```
error:  cannot get a slot ("address") from an object of type "double"
```

Which is an error from the `GET_SLOT` function from Rdefines.h which currently has me stumped.  Have I missed something?  Have you had any thoughts about how one could convert an SEXP matrix in to a `big.matrix` from the C++ side?  It would seem terribly inefficient if we are stuck returning a full R matrix and then converting with `as.big.matrix` on the R side.

**Comment by kaneplusplus** [comment]
`make_double_ptr` takes either a `matrix` or `big.matrix` and returns a pointer to the underlying C-array. Your code is getting the pointer and then returning the `matrix` or `big.matrix` object. Did you mean to return pC?

**Comment by cdeterman** [comment]
I am trying to have it return a `big.matrix` object so that the output would be:

```
An object of class "big.matrix"
Slot "address":
<pointer: 0x4aed070>
```

I was trying to mirror `dgemm` but I cannot figure out how to return `pC` correctly for it to work properly.

**Comment by kaneplusplus** [comment]
OK, but the error in your original post indicates that you're trying to the value of the address slot (which a big.matrix object maintains) from a pointer to doubles. My guess is that `C` is not a `big.matrix` but `C_isBM` is `TRUE`.

**Comment by cdeterman** [comment]
I see, I misunderstood the `make_double_ptr` function then.  Is there a means to convert a SEXP object (i.e. `C`) to a `big.matrix` object then?

**Comment by kaneplusplus** [comment]
Ahh, sorry this isn't documented. `make_double_ptr` takes either a `matrix` or `big.matrix` as the first argument and a boolean letting me know if it is a `big.matrix`. From there I return the address of the beginning of the data.

It might be nice to get rid of the boolean argument by checking to see if the object is a big.matrix. When I originally wrote it though I didn't see a quick way of doing it and this was an easy fix.

**Comment by cdeterman** [comment]
So, does that mean there currently isn't a way to convert from a `matrix` to `big.matrix` object in C++ at the moment?  That is the problem I am trying to solve.  `C` is just a `matrix` at the moment and I want to know if there is any way to convert it to a `big.matrix` and return it to R as such.

**Comment by kaneplusplus** [comment]
You could create a `big.matrix` and populate it with `memcpy` or you could pre-allocate it and pass it to the function.

**Comment by cdeterman** [comment]
Alright, perhaps you can help me work through this.  I pass in a pre-allocated `big.matrix` `C`.  I create a new matrix `Cm` within the C++ code.  I gain access to `C` with `Rcpp`

```
Rcpp::XPtr<BigMatrix> xpC(C);
```

I then populate that matrix with `memcpy`

```
memcpy(xpC->matrix(), &Cm, NN*MM*sizeof(double));
```

How do I return the filled matrix as a `big.matrix` in R?  I apologize if I am missing something elementary here.

**Comment by kaneplusplus** [comment]
It's no problem. What you're doing can be tricky. With Rcpp you should be able to return `xpC`. The return type of the function can be an `SEXP`.

If you don't get this right away would you mind putting up a gist? I'm happy to help you work through this and a complete code example will probably help.

**Comment by cdeterman** [comment]
There are some particulars that make it difficult for a gist as the headers involved with `RcppArmadillo` change `bigalgebra` a bit.  I have pushed my changes to my fork of `bigalgebra`.  It should compile without a problem if you clone it and try locally.  The function of interest is dgemm_wrapper2 in bigalgebra.cpp.

I am then trying the following

```
mat <- matrix(1:9, 
          ncol = 3, 
          nrow = 3, 
          dimnames = list(letters[1:3], LETTERS[1:3]))
mat2 <- matrix(1:9, 
          ncol = 3, 
          nrow = 3, 
          dimnames = list(letters[1:3], LETTERS[1:3]))

bm <- as.big.matrix(mat, type="double")
bm2 <- as.big.matrix(mat2, type="double")

C <- bigalgebra:::anon_matrix(3, 3, "double")

bigalgebra:::dgemm_wrapper2(A=bm@address, 
                        B=bm2@address, 
                        C=C@address,
                        TRUE, TRUE, TRUE)[,]
```

but I get the error:

```
object of type 'externalptr' is not subsettable
```

**Comment by cdeterman** [comment]
After stepping away, I realized I am returning the pointer so I added the line

```
address <- test:::dgemm_wrapper2(bm@address,
                             bm2@address,
                             C@address,
                             TRUE, TRUE, TRUE)

new("big.matrix", address=address)[,]
```

But for some reason, the conversion doesn't work completely as the output is this:

```
          [,1]          [,2] [,3]
[1,] 6.365987e-314 6.084186e-310   42
[2,] 4.446591e-323  3.000000e+01   66
[3,] 6.953162e-310  3.600000e+01   81
```

I have confirmed that the matrix `Cm` in:

```
memcpy(xpC->matrix(), &Cm, NN*MM*sizeof(double));
```

is in fact the correct matrix.  To make this more compact, I have updated my scratch repo 'test' to include all that is needed.  Note, if you try to compile you may need to update your `BigMatrix.h` file to include the following `undef` at the beginning.

```
#ifdef INT
#undef INT
#endif
```

**Comment by cdeterman** [comment]
I have found a solution for the time being.  If I create a `matrixAccessor` object I can then use the following loop:

```
  for (int i = 0; i < MM; i++){
    std::memcpy(C_BM[i], Cm.colptr(i), NN*sizeof(double));
  }
```

Ideally I think it would be preferable if there was a way to avoid the loop.  If you have any thoughts on that, feel free, otherwise this works.

**Comment by kaneplusplus** [comment]
If the `big.matrix` object is column separated then this is unavoidable. Otherwise it can be done with a single memcpy from the address returned by `C_BM.matrix()`.
