### ISSUE TITLE
irlba (SVD) not work for big.matrix

### ISSUE THREAD

**Issue by randel** [kaneplusplus/bigalgebra#5]
Hi Michael,

I tried the example of `irlba()` for SVD but got the following error. Is it because of the update of `irlba()`? Thanks!
`Error in mult(A, VJ) : requires numeric/complex matrix/vector arguments`

https://github.com/kaneplusplus/bigalgebra/blob/04f33104823481c9e473b3c51972cecc3058e355/inst/doc/vignettes/bigalgebra.Rnw#L246

**Comment by kaneplusplus** [comment]
Yes, the `matmul` argument is not the `mult` argument. I've updated the vignette.
